services:
  frontend-service:
    image: frontend-app
    container_name: frontend
    build:
      context: ./frontend-app
    ports:
      - "3000:${PORT}"
    depends_on:
      - backend-service
    networks:
      - poll-system-network

  backend-service:
    image: backend-app
    container_name: backend
    build:
      context: ./backend-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database-service:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - database-service
    networks:
      - poll-system-network
  
  database-service:
    image: postgres:13
    container_name: database
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - poll-system-network

networks:
  poll-system-network:
    name: poll-system-network
    driver: bridge
    
    